name: Build & Release

on:
  push:
    branches:
      - main
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build --if-present

      - name: Create Zip
        run: mkdir temp && zip -r temp/zaity.zip lib package.json LICENSE

      - name: Release
        id: release_gen_step
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Prepare release assets
        id: assets_preparation
        if: steps.release_gen_step.outcome == 'success'
        run: |
          zip -r zaity.zip lib README.md package.json LICENSE logolibrary.svg
