name: Maintenance

on:
  push:
    branches:
      - feature/**
      - fix/**
      - docs/**
      - refactor/**
      - test/**
      - ci/**
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"
      - name: Intall dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
